### PR TITLE
Hotfix 1.12.7

### LINKED ISSUE #217: Line Linked Color not working when string
```json
{
  "particles": {
    "number": {
      "value": 80,
      "density": {
        "enable": true,
        "value_area": 800
      }
    },
    "color": {
      "value": "#ffd700"
    },
    "shape": {
      "type": "circle",
      "stroke": {
        "width": 0,
        "color": "#000000"
      },
      "polygon": {
        "nb_sides": 5
      },
      "image": {
        "src": "img/github.svg",
        "width": 100,
        "height": 100
      }
    },
    "opacity": {
      "value": 0.5,
      "random": false,
      "anim": {
        "enable": false,
        "speed": 1,
        "opacity_min": 0.1,
        "sync": false
      }
    },
    "size": {
      "value": 3,
      "random": true,
      "anim": {
        "enable": false,
        "speed": 40,
        "size_min": 0.1,
        "sync": false
      }
    },
    "line_linked": {
      "enable": true,
      "distance": 150,
      "color": "#000000",
      "opacity": 0.4,
      "width": 1
    },
    "move": {
      "enable": true,
      "speed": 1,
      "direction": "none",
      "random": false,
      "straight": false,
      "out_mode": "out",
      "bounce": false,
      "attract": {
        "enable": false,
        "rotateX": 600,
        "rotateY": 1200
      }
    }
  },
  "interactivity": {
    "detect_on": "canvas",
    "events": {
      "onhover": {
        "enable": false,
        "mode": "repulse"
      },
      "onclick": {
        "enable": true,
        "mode": "push"
      },
      "resize": true
    },
    "modes": {
      "grab": {
        "distance": 400,
        "line_linked": {
          "opacity": 1
        }
      },
      "bubble": {
        "distance": 400,
        "size": 40,
        "duration": 2,
        "opacity": 8,
        "speed": 3
      },
      "repulse": {
        "distance": 200,
        "duration": 0.4
      },
      "push": {
        "particles_nb": 4
      },
      "remove": {
        "particles_nb": 2
      }
    }
  },
  "retina_detect": true,
  "background": {
    "color": "#111",
    "image": "",
    "position": "50% 50%",
    "repeat": "no-repeat",
    "size": "cover"
  }
}
```

This config doesn't set the line linked color. Using `color.value` works instead.

Reported here https://github.com/Wufe/react-particles-js/issues/111 by @elmaxe

### PR DESCRIPTION
**Pull request by matteobruni**

### CODE REVIEW

**Comment by matteobruni** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5316765&bid=17399547)

File: src/index.ts [hunk 1]
```diff
@@ -88,51 +92,54 @@ class Main {
...
+                 * @deprecated this method is obsolete, please use the new tsParticles.load
+                 * @param tagId the particles container element id
+                 * @param params the options object to initialize the [[Container]]
+                 */
+                window.particlesJS = (tagId: string, params: RecursivePartial<IOptions>) => {
+                    tsParticles.load(tagId, params);
+                };
+
+                /**
+                 * Loads the provided json with a GET request. The content will be used to create a [[Container]] object.
```
Comment (matteobruni) [inline src/index.ts:112]: Codacy Issue found: [Exceeds maximum line length of 120](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5316765)
