### PR TITLE
Release 1.11.0

### LINKED ISSUE #61: Refactor var names in CamelCase
Referencing issue https://github.com/VincentGarreau/particles.js/issues/414 from old project

> Need to refactor some var names and function to make happy codacy

@thomas-demagny are we ok here?

### LINKED ISSUE #63: Initialize particles after destroy
Referencing issue https://github.com/VincentGarreau/particles.js/issues/405

> 
> 
> I am aware of the way of destroying particles as described in #63
> After destroying, it is not possible anymore to initialize and start particles because of the error `TypeError: Cannot read property 'push' of null `
> 
> Codesandbox example: https://codesandbox.io/s/quirky-black-yc3fg
> 
> How to reproduce:
> 
>     1. click on start button to start the particles (everything is okay)
> 
>     2. click on destroy button to destroy the particles (everything is okay)
> 
>     3. click on start button to start the particles again (not working)

@dekadentno can you try your issue with this library? Does the bug still exist?

### LINKED ISSUE #102: Particles Shadow
I started working on a shadow implementation, but when I tested it the performance was really poor because of the shadow, not only the shadowBlur.
If someone has an idea to improve that it's really welcome.
I'll do more research about, but the issue is open to be shared.

### LINKED ISSUE #134: tsParticles Default values
The default values are ugly as hell. Some nicer are needed to init library with a good default effect.
Less options enabled is the best solution, so they don't create conflicts.

To change the default values only the classes under Options folder needs changes.

### LINKED ISSUE #141: Multiple polygons shapes permitted
The polygon shape option atm is a single object, it should become an array allowing multiples polygons

### LINKED ISSUE #142: Touch-Drag mobile pushes particles
With mobile devices if you move with your finger around at the release particles will be pushed if push is enabled on click.
This behavior must be fixed, if you’re moving you don’t want pushes

### LINKED ISSUE #143: Unify color management
The color properties in the options are not aligned, they should instead use the same properties and values possibilities.

Thanks to @calebfergie it's interesting to have a more customizable opacity. This could be integrated in the color options instead of being separated.

The random color/opacity options should be a boolean option and not a "random" string. LineLinked have a valid "mid" value that creates a gradient from p1 to p2 based on radius difference, this should be a boolean instead of a string "mid"

### LINKED ISSUE #153: Improve library output files
The library uses babel + webpack to build its output files but they'll be condensed in a single big file.
The output file is currently including *pathseg* library too and I think this is not a best practice.

If I want to add a webGL library in the future this will be a big issue so this need to be improved.

### LINKED ISSUE #156: More customizable strokes
Thanks to @calebfergie I've just seen the random stroke option, it's an interesting option. Every stroke should implement it and the random will be a boolean and not a "random" string value.

### LINKED ISSUE #163: Simple presets
Configs are always painful, a lot of options and often we don't know what they'll change.
A set of presets should implemented and adding them to the config should be clearer and our config can be slimmer and concentrate more on particles number or just a bunch of settings we can change.

```
{
    particles: { number: { value: 100 } },
    preset: 'snow'
}
```

or

```
{
    particles: { number: { value: 100 } },
    preset: ['basic', 'bouncing']
}
```

and we're set.

This will be a great feature for who wants to use the library

### PR DESCRIPTION
**Pull request by matteobruni**

### CODE REVIEW

File: src/Main.ts [hunk 1]
```diff
@@ -1,23 +1,19 @@
...
-import {RecursivePartial} from "./Types/RecursivePartial";
+import type { Container } from "./Classes/Container";
+import { Loader } from "./Classes/Loader";
+import type { IOptions } from "./Interfaces/Options/IOptions";
+import type { RecursivePartial } from "./Types/RecursivePartial";
 
 declare global {
     interface Window {
-        particlesJS: IParticlesJs;
+        particlesJS: any;
```
Comment (matteobruni) [inline src/Main.ts]: Codacy Issue found: [Type declaration of 'any' loses type-safety. Consider replacing it with a more precise type.](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285)

**Comment by matteobruni** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285&bid=17163956)

**Comment by matteobruni** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285&bid=17163956)

File: src/Main.ts (hunk 1 above)
Comment (matteobruni) [inline src/Main.ts]: Codacy Issue found: [Type declaration of 'any' loses type-safety. Consider replacing it with a more precise type.](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285)

**Comment by matteobruni** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285&bid=17163956)

**Comment by matteobruni** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285&bid=17163956)

File: src/Main.ts (hunk 1 above)
Comment (matteobruni) [inline src/Main.ts]: Codacy Issue found: [Type declaration of 'any' loses type-safety. Consider replacing it with a more precise type.](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285)

**Comment by matteobruni** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285&bid=17163956)

File: src/Main.ts (hunk 1 above)
Comment (matteobruni) [inline src/Main.ts]: Codacy Issue found: [Type declaration of 'any' loses type-safety. Consider replacing it with a more precise type.](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285)

**Comment by matteobruni** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285&bid=17163956)

File: src/Main.ts (hunk 1 above)
Comment (matteobruni) [inline src/Main.ts]: Codacy Issue found: [Type declaration of 'any' loses type-safety. Consider replacing it with a more precise type.](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285)

Comment (matteobruni) [inline src/Main.ts]: Codacy Issue found: [Type declaration of 'any' loses type-safety. Consider replacing it with a more precise type.](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285)

**Comment by matteobruni** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5236285&bid=17163956)
