### PR TITLE
fix: make it possible to use a canvas element

### LINKED ISSUE #517: It's not possible to use a canvas element instead of a div
**Describe the bug**
I noticed that it's not possible to use a canvas element instead of a div to initialize tsparticles. I did some digging and it seems [this if check](https://github.com/matteobruni/tsparticles/blob/f6d4c804df68dbf9ef96e4c0957374015df67d26/core/tsparticles/src/Core/Loader.ts#L106) is wrong. [Element.tagName](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName) returns uppercased values.

**To Reproduce**
1. Open one of the codepens
2. Change the div container to a canvas element
3. ???
4. White screen

**Expected behavior**
It should initialise properly

**Desktop (please complete the following information):**
 - OS: OpenSuse
 - Browser Firefox
 - Version 77

### PR DESCRIPTION
**Pull request by Windvis**
This makes it possible to also use a canvas element when initializing
tsparticles

Issue: https://github.com/matteobruni/tsparticles/issues/517

### CODE REVIEW

File: core/tsparticles/src/Core/Loader.ts [hunk 1]
```diff
@@ -103,7 +103,7 @@ export class Loader {
         let canvasEl: HTMLCanvasElement;
         let generatedCanvas: boolean;
 
-        if (domContainer.tagName === "canvas") {
+        if (domContainer.tagName === "CANVAS") {
```
Comment (matteobruni) [inline core/tsparticles/src/Core/Loader.ts:106]: I think .toLower() is a cleaner solution

**Review by matteobruni — CHANGES_REQUESTED** [review]

File: core/tsparticles/src/Core/Loader.ts (hunk 1 above)
Comment (Windvis) [reply core/tsparticles/src/Core/Loader.ts]: I changed it, but tastes differ I guess :smile:.

**Review by matteobruni — APPROVED** [review]

**Comment by matteobruni** [comment]
This will be merged into master for the critical fix. This will be released when #515 will be ready.
