### PR TITLE
splitted updater.ts, fixed movements bugs

### LINKED ISSUE #37: Parallax
The parallax was in development when I forked the source repo, in fact it has some issues keeping the particles aligned.

### LINKED ISSUE #52: Particles speed
The particles speed sometimes can be faster than the original project. The issue is related to the introduction of fps_limit and delta.
The delta is the difference between the last timestamp of animation and the current timestamp so it depends on fps_limit and its framerate blocks. The idea it's fine but comparing the original project they're faster and can be messy with the old configs.

### PR DESCRIPTION
**Pull request by matteobruni**

### CODE REVIEW

File: src/Classes/Particle/Attracter.ts [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+            const ax = dx / (options.particles.move.attract.rotateX * 1000);
+            const ay = dy / (options.particles.move.attract.rotateY * 1000);
+
+            particle.velocity.horizontal -= ax;
+            particle.velocity.vertical -= ay;
+            p2.velocity.horizontal += ax;
+            p2.velocity.vertical += ay;
+        }
+    }
+}
```
Comment (matteobruni) [inline src/Classes/Particle/Attracter.ts]: Codacy Issue found: [file should end with a newline](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5110333)

**Comment by matteobruni** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5110333&bid=16804351)

File: src/Classes/Particle/Bouncer.ts [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+        const distP = particle.radius + p2.radius;
+
+        if (dist <= distP) {
+            particle.velocity.horizontal = -particle.velocity.horizontal;
+            particle.velocity.vertical = -particle.velocity.vertical;
+            p2.velocity.horizontal = -p2.velocity.horizontal;
+            p2.velocity.vertical = -p2.velocity.vertical;
+        }
+    }
+}
```
Comment (matteobruni) [inline src/Classes/Particle/Bouncer.ts]: Codacy Issue found: [file should end with a newline](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5110333)

File: src/Classes/Particle/Linker.ts [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+                /* path */
+                ctx.beginPath();
+                ctx.moveTo(x1, y1);
+                ctx.lineTo(x2, y2);
+                ctx.stroke();
+                ctx.closePath();
+            }
+        }
+    }
+}
```
Comment (matteobruni) [inline src/Classes/Particle/Linker.ts]: Codacy Issue found: [file should end with a newline](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5110333)

**Comment by matteobruni** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5110333&bid=16804351)

File: src/Classes/Particle/Attracter.ts (hunk 1 above)
Comment (matteobruni) [inline src/Classes/Particle/Attracter.ts]: Codacy Issue found: [file should end with a newline](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5110333)

File: src/Classes/Particle/Linker.ts (hunk 3 above)
Comment (matteobruni) [inline src/Classes/Particle/Linker.ts]: Codacy Issue found: [file should end with a newline](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5110333)

File: src/Classes/Particle/Bouncer.ts (hunk 2 above)
Comment (matteobruni) [inline src/Classes/Particle/Bouncer.ts]: Codacy Issue found: [file should end with a newline](https://app.codacy.com/manual/ar3s/tsparticles/pullRequest?prid=5110333)
