### PR TITLE
fix: replaceColor option on image particle, fixes #1519

### LINKED ISSUE #1519: replaceColor option on image particle type not working.
**Which version are you using?**
1.26.3

**Is the latest version affected?**
- [x] Yes
- [ ] No

**Which library are you using?**

- [x] React (`react-tsparticles`)

<details>
 <summary><b>tsParticles Configuration:</b></summary>
  
  ```javascript
{
    background: {
        color: {
            value: 'transparent',
        },
        repeat: 'no-repeat',
        size: 'cover',
    },
    fullScreen: {
        enable: true,
        zIndex: 0,
    },
    particles: {
        collisions: {
            enable: true,
        },
        shape: {
            type: 'images',
            fill: true,
        },
        color: {
            value: '#ffffff',
        },
        move: {
            angle: {
                offset: 0,
                value: 0,
            },
            direction: 'bottom',
            enable: true,
            path: {
                clamp: false,
            },
            outModes: {
                bottom: 'out',
                left: 'out',
                right: 'out',
                top: 'out',
            },
            speed: 3.5,
        },
        number: {
            value: 50,
        },
        size: {
            random: {
                enable: true,
            },
            value: {
                min: 14,
                max: 18,
            },
        },
    },
};
  ```
</details>

**Describe the bug**
I'm trying to dynamically render SVGs as particles, I'm able to do so, however I'm having trouble trying to change their color.
I've tried a mix and match of different configurations to no avail. I've read the documentation over @ [particles.js.org](https://particles.js.org/docs/interfaces/_options_interfaces_particles_shape_iimageshape_.iimageshape.html#replacecolor) and also tried the deprecated options with no success.

I also tried the `fill` option that is passed to the image object, I wasn't sure if it was supposed to have the same behavior as `replaceColor` so I tried it as well and had no success.

On the `<Particles />` component imported from `'react-tsparticles'` I passed an `init` function much like so:

```
    const onInit = async Main => {
        if (Main) {
            const logoImgObjs = logoUrls
                .filter(e => e)
                .map(e => {
                    return {
                        src: e,
                        width: 400,
                        height: 400,
                        replaceColor: true,
                        fill: true,
                    };
                });

            const configWithImages = {
                ...tsParticlesConfigObj,
                particles: {
                    ...tsParticlesConfigObj.particles,
                    shape: {
                        ...tsParticlesConfigObj.particles.shape,
                        type: 'images',
                        images: logoImgObjs,
                    },
                },
            };

            const particlesInstance = await Main.load(id, configWithImages);
            particlesInstance?.refresh();
        }
    };
```

The only way I was able to change the color of the SVG was by modifying the `ImageDrawer.ts` file on `\tsparticles\core\main\src\ShapeDrawers\ImageDrawer.ts`

```
    private async loadImageShape(container: Container, imageShape: IImageShape): Promise<void> {
        try {
            let image = imageShape.replaceColor
                ? await Utils.downloadSvgImage(imageShape.src)
                : await Utils.loadImage(imageShape.src);

            if (image) {
                if (imageShape.replaceColor) {
                    image = {
                        ...image,
                        svgData: `${image.svgData?.substring(0, image.svgData.indexOf(">"))} fill="${
                            container.actualOptions.particles.color.value
                        }"${image.svgData?.substring(image.svgData.indexOf(">"))}`,
                    };
                }
                this.addImage(container, image);
            }
        } catch {
            console.warn(`tsParticles error - ${imageShape.src} not found`);
        }
    }
```

This way it works perfectly, but I decided not to open a PR with this fix because I suck at coding and there's probably a better way to do it than gluing strings together with substring.

**To Reproduce**
1. Pretty much just try to render multiple SVGs and try to replace their colors.

**Expected behavior**
Upon passing `fill: true` to the shape configuration and `replaceColor: true` to the configuration of the image shape I expect the SVG color to be replaced with `particles.color.value`.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Brave
 - Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by GoldenMaximo**
@matteobruni 
Hi Matteo,

I created a utility method to replace the SVG color, however I wasn't able to get it to work with RGB and HSL, it only works with HEX so I added a TODO comment about it.

And of course, feel free to comment any inconsistencies or point out anything that you think could have been done in a better way.

### CODE REVIEW

**Comment by GoldenMaximo** [comment]
5c295e6 to 4a19da9:
Updated the title referencing issue #1319 instead of #1519 and changed a return statement DeepCode pointed out.

**Comment by matteobruni** [comment]
I just checked, there's already a `replaceColorSvg` in the `ColorUtils.ts` file. I think if you update that you'll have the fix.

The `ImageDrawer.ts` shouldn't be updated because the `Particle.ts` file already calls it in the particle constructor.

**Review by matteobruni — CHANGES_REQUESTED** [review]
Check out the previous comment

File: core/main/src/Utils/ColorUtils.ts [hunk 1]
```diff
@@ -479,16 +479,33 @@ export class ColorUtils {
...
+        const imageType = source.substr(source.length - 3);
+        if (imageType !== "svg") {
+            throw new Error("Error tsParticles - replaceColor property provided to non-.svg image.src");
         }
 
         /* set color to svg element */
-        const svgXml = image.svgData;
-        const rgbHex = /#([0-9A-F]{3,6})/gi;
+        if (svgData.includes("fill")) {
+            const currentColor = /(#(?:[0-9a-f]{2}){2,4}|(#[0-9a-f]{3})|(rgb|hsl)a?\((-?\d+%?[,\s]+){2,3}\s*[\d.]+%?\)|currentcolor)/i;
```
Comment (GoldenMaximo) [inline core/main/src/Utils/ColorUtils.ts]: Originally I indented to use a much larger [regex](https://gist.github.com/olmokramer/82ccce673f86db7cda5e) that also encompasses color names like "black, orange, pink" etc. But I didn't know where to put it (which file to export it from) so I used this one here which is much shorter, and as for string names, I left only "currentcolor" since I noticed it's the default value on [Boostrap Icons](https://icons.getbootstrap.com/)

**Comment by GoldenMaximo** [comment]
@matteobruni I updated the PR with some refactoring.

I think that the problem was that the original `replaceColorSvg` function did not account for the possibility of the loaded SVG not having a pre-set fill and the previously used regex in that function, meant to match and replace the SVG fill color, only accounted for HEX values, so if the SVG had no fill or had any fill other than hex the function wouldn't replace the SVG's color.

File: core/main/src/Utils/ColorUtils.ts [hunk 2]
```diff
@@ -479,16 +479,33 @@ export class ColorUtils {
         };
     }
 
-    static replaceColorSvg(image: IImage, color: IHsl, opacity: number): string {
-        if (!image.svgData) {
-            return "";
+    static replaceColorSvg(imageShape: IImage, color: IHsl, opacity: number): string {
+        if (!imageShape) {
```
Comment (matteobruni) [inline core/main/src/Utils/ColorUtils.ts]: This is unnecessary, the image shape should be already checked outside.

File: core/main/src/Utils/ColorUtils.ts [hunk 3]
```diff
@@ -479,16 +479,33 @@ export class ColorUtils {
...
+        }
+
+        const { source, svgData } = imageShape;
+        if (!source || !svgData) {
+            throw new Error("Error tsParticles - No image.src");
+        }
+
+        const imageType = source.substr(source.length - 3);
+        if (imageType !== "svg") {
+            throw new Error("Error tsParticles - replaceColor property provided to non-.svg image.src");
```
Comment (matteobruni) [inline core/main/src/Utils/ColorUtils.ts]: No need to throw an error, ignore if is not a SVG image

File: core/main/src/Utils/ColorUtils.ts (hunk 1 above)
Comment (matteobruni) [reply core/main/src/Utils/ColorUtils.ts]: `currentcolor` is not a valid value for `getStyleFromHsl`, I think it can be ignored

File: core/main/src/Utils/ColorUtils.ts [hunk 4]
```diff
@@ -479,16 +479,33 @@ export class ColorUtils {
...
         }
 
         /* set color to svg element */
-        const svgXml = image.svgData;
-        const rgbHex = /#([0-9A-F]{3,6})/gi;
+        if (svgData.includes("fill")) {
```
Comment (matteobruni) [inline core/main/src/Utils/ColorUtils.ts:489]: I don't understand this if, why are you searching for `fill`?

File: core/main/src/Utils/ColorUtils.ts [hunk 5]
```diff
@@ -479,16 +479,33 @@ export class ColorUtils {
...
+            const currentColor = /(#(?:[0-9a-f]{2}){2,4}|(#[0-9a-f]{3})|(rgb|hsl)a?\((-?\d+%?[,\s]+){2,3}\s*[\d.]+%?\)|currentcolor)/i;
+            return svgData.replace(currentColor, () => ColorUtils.getStyleFromHsl(color, opacity));
+        }
+
+        const coloredSvgData = `${svgData.substring(0, svgData.indexOf(">"))} fill="${ColorUtils.getStyleFromHsl(
```
Comment (matteobruni) [inline core/main/src/Utils/ColorUtils.ts:494]: This is not clear to me too. Can you give more details? A sample is enough I think.

**Review by matteobruni — CHANGES_REQUESTED** [review]
I've seen the changes, they are not all crystal clear but I commented lines.
Can you run `lerna run build` in the folder before committing/pushing so the linter will run. I see some indentation issues that are not following the standards (or GH messed up with the viewer)

File: core/main/src/Utils/ColorUtils.ts (hunk 4 above)
Comment (GoldenMaximo) [reply core/main/src/Utils/ColorUtils.ts:489]: The icons @ https://simpleicons.org/ I'm using have no pre-set fill, so when the previous code ran looking for a rgbHex it found none, therefore it didn't change the color of the SVG, leaving it as the default black.

File: core/main/src/Utils/ColorUtils.ts (hunk 5 above)
Comment (GoldenMaximo) [reply core/main/src/Utils/ColorUtils.ts:494]: If there is no fill on the SVG, it will split the string at the the end of the first tag <svg> and give it a fill property containing the new color.

File: core/main/src/Utils/ColorUtils.ts (hunk 4 above)
Comment (matteobruni) [reply core/main/src/Utils/ColorUtils.ts:489]: Ah ok, if there's no fill you'll add it, am I right? This is a good idea!

**Comment by GoldenMaximo** [comment]
> I've seen the changes, they are not all crystal clear but I commented lines.
> Can you run `lerna run build` in the folder before committing/pushing so the linter will run. I see some indentation issues that are not following the standards (or GH messed up with the viewer)

I ran `lerna run build`
image

It changed some indentation on some test file, should I add it with this PR as a commit?

**Review by matteobruni — APPROVED** [review]
Looks good to me, This will be in the `1.27.0` release (PR #1521)
