### PR TITLE
Release 1.13.7

### LINKED ISSUE #289: Browser focus change unpauses particles
**Describe the bug**

When using the `pause` method on the `particles` instance in my codebase, it does pause as-expected. However, when I switch tabs and come back to the same tab, it resumes without me asking it to

**To Reproduce**

Use this site:

https://github.com/crutchcorn/gitshark-website/tree/f807a340542c3e7f41055398c6b7973fe4d0331b

Press "Pause motion", change tabs, then come back

**Expected behavior**

It would be ideal if the particles stayed paused

**Desktop (please complete the following information):**
 Windows 10 Chrome 81

### PR DESCRIPTION
**Pull request by matteobruni**
Fixes issue #289

### CODE REVIEW

File: src/Classes/FrameManager.ts [hunk 1]
```diff
@@ -22,6 +22,8 @@ export class FrameManager {
 
         const delta = timestamp - container.lastFrameTime;
 
+        console.log(delta, container.lastFrameTime, timestamp);
```
Comment (crutchcorn) [inline src/Classes/FrameManager.ts:25]: Can we remove this console.log? It flooding my production environment 😅

Comment (matteobruni) [reply src/Classes/FrameManager.ts:25]: Ops, yeah sure I'm releasing a 1.13.8 for another bug I found
